In [1]:
import pandas as pd
pd.read_csv(filepath_or_buffer = "last_step.csv")

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,issue_d - year
0,54734,80364,25000,25000,19080.057200,36 months,0.1189,829.10,B,B4,...,01-08-2009,Fully Paid,n,Due to a lack of personal finance education an...,debt_consolidation,Debt consolidation for on-time payer,941xx,CA,19.48,2009
1,55742,114426,7000,7000,672.803839,36 months,0.1071,228.22,B,B5,...,01-05-2008,Fully Paid,n,Just want to pay off the last bit of credit ca...,credit_card,Credit Card payoff,112xx,NY,14.29,2008
2,57245,138150,1200,1200,1200.000000,36 months,0.1311,40.50,C,C2,...,01-03-2010,Fully Paid,n,"If funded, I would use this loan consolidate t...",debt_consolidation,zxcvb,777xx,TX,5.47,2010
3,57416,139635,10800,10800,10691.551050,36 months,0.1357,366.86,C,C3,...,01-11-2009,Fully Paid,n,I currently have a personal loan with Citifina...,debt_consolidation,Nicolechr1978,067xx,CT,11.63,2009
4,58915,153417,7500,5025,557.087228,36 months,0.1008,162.34,B,B3,...,01-04-2008,Fully Paid,n,Hi : Thanks for stopping by. I've accr...,debt_consolidation,sdguy,921xx,CA,8.10,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39712,1075358,1311748,3000,3000,3000.000000,60 months,0.1269,67.79,B,B5,...,01-12-2011,Current,n,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,2011
39713,1076863,1277178,10000,10000,10000.000000,36 months,0.1349,339.31,C,C1,...,01-12-2011,Fully Paid,n,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,2011
39714,1077175,1313524,2400,2400,2400.000000,36 months,0.1596,84.33,C,C5,...,01-12-2011,Fully Paid,n,NaN,small_business,real estate business,606xx,IL,8.72,2011
39715,1077430,1314167,2500,2500,2500.000000,60 months,0.1527,59.83,C,C4,...,01-12-2011,Charged Off,n,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,2011
39716,1077501,1296599,5000,5000,4975.000000,36 months,0.1065,162.87,B,B2,...,01-12-2011,Fully Paid,n,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,2011

In [2]:
df=pd.read_csv(filepath_or_buffer = "last_step.csv")

In [3]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,issue_d - year
0,54734,80364,25000,25000,19080.057200,36 months,0.1189,829.10,B,B4,...,01-08-2009,Fully Paid,n,Due to a lack of personal finance education an...,debt_consolidation,Debt consolidation for on-time payer,941xx,CA,19.48,2009
1,55742,114426,7000,7000,672.803839,36 months,0.1071,228.22,B,B5,...,01-05-2008,Fully Paid,n,Just want to pay off the last bit of credit ca...,credit_card,Credit Card payoff,112xx,NY,14.29,2008
2,57245,138150,1200,1200,1200.000000,36 months,0.1311,40.50,C,C2,...,01-03-2010,Fully Paid,n,"If funded, I would use this loan consolidate t...",debt_consolidation,zxcvb,777xx,TX,5.47,2010
3,57416,139635,10800,10800,10691.551050,36 months,0.1357,366.86,C,C3,...,01-11-2009,Fully Paid,n,I currently have a personal loan with Citifina...,debt_consolidation,Nicolechr1978,067xx,CT,11.63,2009
4,58915,153417,7500,5025,557.087228,36 months,0.1008,162.34,B,B3,...,01-04-2008,Fully Paid,n,Hi : Thanks for stopping by. I've accr...,debt_consolidation,sdguy,921xx,CA,8.10,2008

In [5]:
df.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,issue_d - year
39712,1075358,1311748,3000,3000,3000.0,60 months,0.1269,67.79,B,B5,...,01-12-2011,Current,n,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,2011
39713,1076863,1277178,10000,10000,10000.0,36 months,0.1349,339.31,C,C1,...,01-12-2011,Fully Paid,n,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,2011
39714,1077175,1313524,2400,2400,2400.0,36 months,0.1596,84.33,C,C5,...,01-12-2011,Fully Paid,n,NaN,small_business,real estate business,606xx,IL,8.72,2011
39715,1077430,1314167,2500,2500,2500.0,60 months,0.1527,59.83,C,C4,...,01-12-2011,Charged Off,n,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,2011
39716,1077501,1296599,5000,5000,4975.0,36 months,0.1065,162.87,B,B2,...,01-12-2011,Fully Paid,n,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,2011

In [6]:
df.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,issue_d - year
count,3.971700e+04,3.971700e+04,39717.000000,39717.000000,39717.000000,39717.000000,39717.000000,3.971700e+04,39717.000000,39717.000000
mean,6.831319e+05,8.504636e+05,11219.443815,10947.713196,10397.448868,0.120212,324.561922,6.896893e+04,13.315130,2010.328902
std,2.106941e+05,2.656783e+05,7456.670694,7187.238670,7128.450439,0.037248,208.874874,6.379377e+04,6.678594,0.877514
min,5.473400e+04,7.069900e+04,500.000000,500.000000,0.000000,0.054200,15.690000,4.000000e+03,0.000000,2007.000000
25%,5.162210e+05,6.667800e+05,5500.000000,5400.000000,5000.000000,0.092500,167.020000,4.040400e+04,8.170000,2010.000000
50%,6.656650e+05,8.508120e+05,10000.000000,9600.000000,8975.000000,0.118600,280.220000,5.900000e+04,13.400000,2011.000000
75%,8.377550e+05,1.047339e+06,15000.000000,15000.000000,14400.000000,0.145900,430.780000,8.230000e+04,18.600000,2011.000000
max,1.077501e+06,1.314167e+06,35000.000000,35000.000000,35000.000000,0.245900,1305.190000,6.000000e+06,29.990000,2011.000000

In [7]:
df.info

<bound method DataFrame.info of             id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
0        54734      80364      25000        25000     19080.057200
1        55742     114426       7000         7000       672.803839
2        57245     138150       1200         1200      1200.000000
3        57416     139635      10800        10800     10691.551050
4        58915     153417       7500         5025       557.087228
...        ...        ...        ...          ...              ...
39712  1075358    1311748       3000         3000      3000.000000
39713  1076863    1277178      10000        10000     10000.000000
39714  1077175    1313524       2400         2400      2400.000000
39715  1077430    1314167       2500         2500      2500.000000
39716  1077501    1296599       5000         5000      4975.000000

             term  int_rate  installment grade sub_grade  ...     issue_d  \
0       36 months    0.1189       829.10     B        B4  ...  01-08-2009
1       36 months    0.1071       228.22     B        B5  ...  01-05-2008
2       36 months    0.1311        40.50     C        C2  ...  01-03-2010
3       36 months    0.1357       366.86     C        C3  ...  01-11-2009
4       36 months    0.1008       162.34     B        B3  ...  01-04-2008
...           ...       ...          ...   ...       ...  ...         ...
39712   60 months    0.1269        67.79     B        B5  ...  01-12-2011
39713   36 months    0.1349       339.31     C        C1  ...  01-12-2011
39714   36 months    0.1596        84.33     C        C5  ...  01-12-2011
39715   60 months    0.1527        59.83     C        C4  ...  01-12-2011
39716   36 months    0.1065       162.87     B        B2  ...  01-12-2011

       loan_status pymnt_plan  \
0       Fully Paid          n
1       Fully Paid          n
2       Fully Paid          n
3       Fully Paid          n
4       Fully Paid          n
...            ...        ...
39712      Current          n
39713   Fully Paid          n
39714   Fully Paid          n
39715  Charged Off          n
39716   Fully Paid          n

                                                    desc             purpose  \
0      Due to a lack of personal finance education an...  debt_consolidation
1      Just want to pay off the last bit of credit ca...         credit_card
2      If funded, I would use this loan consolidate t...  debt_consolidation
3      I currently have a personal loan with Citifina...  debt_consolidation
4      Hi :         Thanks for stopping by. I've accr...  debt_consolidation
...                                                  ...                 ...
39712    Borrower added on 12/21/11 > I plan on combi...               other
39713    Borrower added on 12/21/11 > to pay for prop...               other
39714                                                NaN      small_business
39715    Borrower added on 12/22/11 > I plan to use t...                 car
39716    Borrower added on 12/22/11 > I need to upgra...         credit_card

                                      title zip_code addr_state    dti  \
0      Debt consolidation for on-time payer    941xx         CA  19.48
1                        Credit Card payoff    112xx         NY  14.29
2                                     zxcvb    777xx         TX   5.47
3                             Nicolechr1978    067xx         CT  11.63
4                                     sdguy    921xx         CA   8.10
...                                     ...      ...        ...    ...
39712                              Personal    972xx         OR  17.94
39713                              personel    917xx         CA  20.00
39714                  real estate business    606xx         IL   8.72
39715                                  bike    309xx         GA   1.00
39716                              Computer    860xx         AZ  27.65

      issue_d - year
0               2009
1               2008
2               2010
3               2009
4               2008
...              ...
39712           2011
39713           2011
39714           2011
39715           2011
39716           2011

[39717 rows x 25 columns]>

In [8]:
df.isnull()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,issue_d - year
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39712,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39713,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39714,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
39715,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39716,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

id                         0
member_id                  0
loan_amnt                  0
funded_amnt                0
funded_amnt_inv            0
term                       0
int_rate                   0
installment                0
grade                      0
sub_grade                  0
emp_title               2459
emp_length              1075
home_ownership             0
annual_inc                 0
verification_status        0
issue_d                    0
loan_status                0
pymnt_plan                 0
desc                   12942
purpose                    0
title                     11
zip_code                   0
addr_state                 0
dti                        0
issue_d - year             0
dtype: int64

In [10]:
df.drop(columns=['desc'], inplace=True)

In [11]:
df['emp_title'].fillna('Unknown', inplace=True)
df['emp_length'].fillna('Unknown', inplace=True)
df['title'].fillna('Unknown', inplace=True)

In [12]:
df['loan_amnt'].fillna(df['loan_amnt'].mean(), inplace=True)

In [13]:
df.isnull().sum()

id                     0
member_id              0
loan_amnt              0
funded_amnt            0
funded_amnt_inv        0
term                   0
int_rate               0
installment            0
grade                  0
sub_grade              0
emp_title              0
emp_length             0
home_ownership         0
annual_inc             0
verification_status    0
issue_d                0
loan_status            0
pymnt_plan             0
purpose                0
title                  0
zip_code               0
addr_state             0
dti                    0
issue_d - year         0
dtype: int64

In [14]:
import pandas as pd
df = pd.read_csv("last_step.csv")

In [15]:
from sqlalchemy import create_engine
username = "root"
password = "Admin"
host = "localhost"
port = "3306"
database = "sbi_bank"
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [16]:
table_name = "public"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'public' in database 'sbi_bank'.